version: 2
jobs:
  install-job:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-json.lock" }}
            - node-modules-
      - run: npm install
      - save_cache:
          key: node-modules-{{ checksum "package-json.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules/*

  lint-job:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm run lint

  build-job:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm run build

workflows:
  version: 2
  build-deploy:
    jobs:
      - install-job:
          filters:
            tags:
              only: /.*/
      - build-job:
          requires:
            - install-job
          filters:
            tags:
              only: /.*/
      - lint-job:
          requires:
            - install-job
          filters:
            tags:
              only: /.*/
