version: 2
jobs:
  install-job:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-json.lock" }}
            - node-modules-
      - run: npm install
      - save_cache:
          key: node-modules-{{ checksum "package-json.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules/*

  lint-job:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm run lint

  build-job:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm run build

  publish-job:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo/packages/react-accessible-tooltip
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish

workflows:
  version: 2
  build-publish:
    jobs:
      - install-job:
          filters:
            tags:
              only: /.*/
      - build-job:
          requires:
            - install-job
          filters:
            tags:
              only: /.*/
      - lint-job:
          requires:
            - install-job
          filters:
            tags:
              only: /.*/
      - publish-job:
          requires:
            - lint-job
            - test-job
            - build-job
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
